### ISSUE TITLE
Unable to generate images other than 512x512 "INVALID_ARGUMENT : Got invalid dimensions for input: latent_model_input"

### ISSUE THREAD

**Issue by JoeShabadu2000** [MerijnvanEijk/stbl-diffusion-gui-onnx#1]
GUI working great for 512x512 images. However, when I change resolutions to anything else, I receive errors.

Here is the output for 256x256:
###

```
Randomizing every seed
Generating 1 images.
[1/1]Running iterations...

0it [00:00, ?it/s]
0it [00:00, ?it/s]
Exception in thread Thread-6 (worker_iterations):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\examples\inference\stbl_gui.py", line 139, in worker_iterations
    stdiff.run()
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\examples\inference\stbl_gui.py", line 112, in run
    self.image = self.pipe(self.prompt, 
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\amd_venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\examples\inference\dml_onnx.py", line 168, in __call__
    noise_pred = unet_sess.run(None, inp)[0]
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\amd_venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: latent_model_input for the following indices
 index: 2 Got: 32 Expected: 64
 index: 3 Got: 32 Expected: 64
 Please fix either the inputs or the model.
```

###

And here is the output for 768x512 (default when opening GUI):
####

```
Randomizing every seed
Generating 1 images.
[1/1]Running iterations...

0it [00:00, ?it/s]
0it [00:00, ?it/s]
Exception in thread Thread-7 (worker_iterations):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\examples\inference\stbl_gui.py", line 139, in worker_iterations
    stdiff.run()
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\examples\inference\stbl_gui.py", line 112, in run
    self.image = self.pipe(self.prompt, 
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\amd_venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\examples\inference\dml_onnx.py", line 168, in __call__
    noise_pred = unet_sess.run(None, inp)[0]
  File "C:\Users\User\Documents\stable-diffusion-amd\diffusers-dml\amd_venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: latent_model_input for the following indices
 index: 3 Got: 96 Expected: 64
 Please fix either the inputs or the model.
```

####

Maybe something needs to be changed on my end? Thank you!

**Comment by MerijnvanEijk** [comment]
The unfortunate thing, it seems at the moment, that the model itself for the save_onnx.py needs to be re-run. At least for images greater then the resolution, that is definitly a must, the smaller ones this also seems the case, but not fully sure why.
So save_onnx.py for the 768x512 at line  66 for me.
```
# Change height and width to create ONNX model file for that size
convert_to_onnx(pipe.unet, pipe.vae.post_quant_conv, pipe.vae.decoder, text_encoder, height=512, width=768)
```
But the smaller(256x256) configured resolution I'd expect would work as its an 4 byte aligned value as well, but it indeed doesn't seem to accept the index. If I re-run the save_onnx.py with 256x256, it does seem to accept 256x256. 

Not sure why the index conversion is fixed at the moment in the dml_onnx.py, I believe the argument in dml_onnx.py would be overridden, but something is wrong there at the moment, not fully sure why yet.
```
    def __call__(
        self,
        prompt: Union[str, List[str]],
        height: Optional[int] = 512,
        width: Optional[int] = 512,
```
If you reconfigure the save_onnx.py for 256, this would also work for you at the moment, but changing resolution would require a reconfiguration of this each time, which is not optimal at this moment.

**Comment by JoeShabadu2000** [comment]
Editing the save_onnx.py file and re-running it does appear to fix the issue for me, although I agree the solution is not optimal. Not a big deal to run the save_onnx file at a higher resolution to start with, but being unable to do a lower resolution without reconfiguring each time is less than ideal. I think it's nice to do some lower resolution passes so that you can refine your keywords, before taking the time to make higher resolution images.

I'll keep an eye out on the repo for updates to see if this is something that gets addressed in a future release. I appreciate the response, as well as your hard work on this project, and thanks very much for your help!

**Comment by Clusters** [comment]
I would suggest to open this again, as I stumbled over it and because the default values of the GUI are triggering this issue, others might as well.
