### ISSUE TITLE
latent_model_input with wrong dimension argument

### ISSUE THREAD

**Issue by Clusters** [MerijnvanEijk/stbl-diffusion-gui-onnx#5]
Running on a Win10x64 machine with ort_nightly_directml-1.13.0.dev20220908001-cp310-cp310-win_amd64.whl

(amd_ai) D:\ai\diffusers\examples\inference>python stbl_gui.py
Fetching 19 files: 100%|█████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 3164.76it/s]
0it [00:00, ?it/s]
Exception in thread Thread-3 (worker_iterations):
Traceback (most recent call last):
  File "C:\Users\_\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\_\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ai\diffusers\examples\inference\stbl_gui.py", line 139, in worker_iterations
    stdiff.run()
  File "D:\ai\diffusers\examples\inference\stbl_gui.py", line 112, in run
    self.image = self.pipe(self.prompt,
  File "D:\ai\amd_ai\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\ai\diffusers\examples\inference\dml_onnx.py", line 168, in __call__
    noise_pred = unet_sess.run(None, inp)[0]
  File "D:\ai\amd_ai\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: latent_model_input for the following indices
 index: 3 Got: 96 Expected: 64
 Please fix either the inputs or the model.

**Comment by Clusters** [comment]
Duplicate to #1 
Would consider opening it, as it is not fixed.
